### PR TITLE
Changes to file structure

### PR DESCRIPTION
**Pull request by vanandsh**
- File structure changed to move EDA to a separate folder
- Pandas profiling issue fixed by creating a link to the profile report
- Removed unused cells

### CODE REVIEW

**Review by jackyho112 — CHANGES_REQUESTED** [review]
1. Try to just display the HTML file in the notebook - https://stackoverflow.com/questions/26462893/import-html-to-ipython-notebook-file

1. Also, why do we need to save all the plot images?

**Comment by vanandsh** [comment]
1. The html file renders fine on the notebook, but it is not visible on github. Hence using a separate link to redirect to the profile report generated by pandas profiling.
2. Removed the additional image files created

**Comment by vanandsh** [comment]
1. The html file renders fine on the notebook, but it is not visible on github. Hence using a separate link to redirect to the profile report generated by pandas profiling.
2. Removed the additional image files created

**Review by jackyho112 — APPROVED** [review]
Looks good!

**Pull request merged**
