### PR TITLE
Added scripts

### PR DESCRIPTION
**Pull request by vanandsh**
- 02_wrangle.py --> Reads the data, removes unwanted columns and finally splits the data into two files train.csv and test.csv
- 03_eda_script.R --> generates plots and figures

### CODE REVIEW

**Review by ofer-m — APPROVED** [review]

**Review by ofer-m — CHANGES_REQUESTED** [review]
Hey Anand, can you please remove the numbers from the file names for the script and images. I thought we were doing a number convention, but we're not. sorry for the misunderstanding. Thanks!

**Review by ofer-m — CHANGES_REQUESTED** [review]
Also, in the eda script, you can remove the following:

library(reshape2)

we are not using this library

**Comment by vanandsh** [comment]
Numbering the file names seems like a good idea. Any reason we want to keep it as before?

**Comment by vanandsh** [comment]
Closing this as new PR will be created that includes all these files.

**Pull request closed without merging**
